export const BANKNAMES_BY_BANKCODES = [
	{ key: '039', value: '경남은행' },
	{ key: '034', value: '광주은행' },
	{ key: '012', value: '단위농협(지역농축협)' },
	{ key: '032', value: '부산은행' },
	{ key: '045', value: '새마을금고' },
	{ key: '064', value: '산림조합' },
	{ key: '088', value: '신한은행' },
	{ key: '048', value: '신협' },
	{ key: '027', value: '씨티은행' },
	{ key: '020', value: '우리은행' },
	{ key: '071', value: '우체국예금보험' },
	{ key: '050', value: '저축은행중앙회' },
	{ key: '037', value: '전북은행' },
	{ key: '035', value: '제주은행' },
	{ key: '090', value: '카카오뱅크' },
	{ key: '089', value: '케이뱅크' },
	{ key: '092', value: '토스뱅크' },
	{ key: '081', value: '하나은행' },
	{ key: '054', value: '홍콩상하이은행' },
	{ key: '003', value: 'IBK기업은행' },
	{ key: '004', value: 'KB국민은행' },
	{ key: '031', value: 'DGB대구은행' },
	{ key: '002', value: 'KDB산업은행' },
	{ key: '011', value: 'NH농협은행' },
	{ key: '023', value: 'SC제일은행' },
	{ key: '007', value: 'Sh수협은행' },
];
