spring:
  # database setting
  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P22C205?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S09P22C205
    password: t47Rd1DnsH
    driver-class-name: org.mariadb.jdbc.Driver
  # h2 setting
  h2:
    console:
      enabled: true
  # jpa setting
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    open-in-view: true

# log setting
logging:
  level:
    org.hibernate.SQL: debug
    com.shinhan.changyo: debug

jwt:
  secret: sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss

changyo-account:
  id: 1
  accountNumber: 110291999999